# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('letra', models.TextField()),
                ('liga', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
